// Hand-drawn pixel-art SVG icons. Each icon is a 24x24 grid of 1x1 unit rects.
// "#" = filled pixel, "." or " " = empty. No external icon library.

type Props = { className?: string };

function pixelIcon(grid: string) {
  const rows = grid.replace(/^\n|\n$/g, "").split("\n");
  const rects: Array<{ x: number; y: number }> = [];
  rows.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === "#") rects.push({ x, y });
    });
  });
  return rects;
}

function PixelArt({
  grid,
  className,
  label,
}: {
  grid: string;
  className?: string;
  label: string;
}) {
  const rects = pixelIcon(grid);
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      role="img"
      aria-label={label}
      shapeRendering="crispEdges"
    >
      {rects.map((p, i) => (
        <rect key={i} x={p.x} y={p.y} width="1" height="1" fill="currentColor" />
      ))}
    </svg>
  );
}

// Code window with bracketed lines. Stands for "open source".
const SOURCE_GRID = `
........................
........................
...##################...
...##################...
...#................#...
...#.######.........#...
...#................#...
...#.####.....####..#...
...#................#...
...#.######.........#...
...#................#...
...#.####...........#...
...#................#...
...##################...
........................
........................
.........####...........
.........####...........
.........####...........
.......########.........
.......########.........
........................
........................
........................
`;

// Terminal-style window with chevron + cursor. Stands for "for humans and agents".
const TERMINAL_GRID = `
........................
........................
..####################..
..####################..
..#..................#..
..#.##................#.
..#..##...............#.
..#.##................#.
..#...................#.
..#......######.......#.
..#...................#.
..#...................#.
..####################..
..####################..
........................
.....##...........##....
.....##...........##....
....####.........####...
........................
.......##########.......
........................
........................
........................
........................
`;

// AST tree: node fanning out to leaves. Stands for "stable, versioned AST".
const AST_GRID = `
........................
........................
..........####..........
..........####..........
..........####..........
..........####..........
..........####..........
.......########.........
.......########.........
......##########........
.....####....####.......
....####......####......
...####........####.....
..####..........####....
..####..........####....
.####............####...
.####............####...
####..............####..
####..............####..
####..............####..
####..............####..
........................
........................
........................
`;

export function SourceIcon({ className }: Props) {
  return <PixelArt grid={SOURCE_GRID} className={className} label="Source" />;
}

export function TerminalIcon({ className }: Props) {
  return <PixelArt grid={TERMINAL_GRID} className={className} label="Terminal" />;
}

export function AstIcon({ className }: Props) {
  return <PixelArt grid={AST_GRID} className={className} label="tree" />;
}
